name: Deploy Application B
on:
  workflow_call:
    secrets:
      ALLOW_DEPLOYMENTS:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Deployment Secret
        id: check
        run: |
          if [ "${{ secrets.ALLOW_DEPLOYMENTS }}" = "false" ]; then
            echo "blocked=true" >> $GITHUB_OUTPUT
          else
            echo "blocked=false" >> $GITHUB_OUTPUT

      - name: Deploy Application B
        if: ${{ steps.check.outputs.blocked == 'false' }}
        run: |
          echo "🚀 Deploying Application B..."
          # Insert deployment steps here

      - name: Deployment Blocked
        if: ${{ steps.check.outputs.blocked == 'true' }}
        run: echo "🚫 Deployment blocked by system administrator."
