name: Deploy Application A
on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Application A
        run: |
          echo "🚀 Deploying Application A..."
          # Insert deployment steps here
