name: Deploy Application A

on:
  workflow_call:
    inputs:
      allow_deployments:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Prep step
        run: echo "🔧 Preparing deployment environment for Application A..."

      - name: Deploy Application A
        if: ${{ inputs.allow_deployments != 'false' }}
        run: |
          echo "🚀 Deploying Application A..."
          # Insert deployment A steps here

      - name: Deployment blocked notice
        if: ${{ inputs.allow_deployments == 'false' }}
        run: echo "🚫 Deployment A skipped because deployments are blocked."
