name: Deploy Application A

on:
  workflow_call:
    secrets:
      ALLOW_DEPLOYMENTS:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Prep step
        run: echo "🔧 Preparing deployment environment for Application A..."

      - name: Deploy Application A
        if: ${{ secrets.ALLOW_DEPLOYMENTS != 'false' }}
        run: |
          echo "🚀 Deploying Application A..."
          # Insert deployment A steps here

      - name: Deployment blocked notice
        if: ${{ secrets.ALLOW_DEPLOYMENTS == 'false' }}
        run: echo "🚫 Deployment A skipped because deployments are blocked."
