name: Deploy Application A

on:
  workflow_call:
    outputs:
      allow:
        description: "Checks to allow deployment."
        value: ${{ jobs.deploy.outputs.allow }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      allow: ${{ steps.check.outputs.allow }}
    steps:
      - name: Check if deployment is allowed
        id: check
        run: |
          if [ -z "${{ secrets.ALLOW_DEPLOYMENT }}" ]; then
            echo "allow=0" >> $GITHUB_OUTPUT
          elif [ "${{ secrets.ALLOW_DEPLOYMENT }}" = "true" ]; then
            echo "allow=1" >> $GITHUB_OUTPUT
          else
            echo "allow=0" >> $GITHUB_OUTPUT
          fi
