name: Deploy Application A

on:
  workflow_call:
    secrets:
      APP_SECRET:
        required: true
      ANOTHER_SECRET:
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Application A
        run: |
          echo "🚀 Deploying Application A..."
          echo "Using ANOTHER_SECRET: ${{ secrets.ANOTHER_SECRET }}"
          
          if [ "${{ secrets.APP_SECRET }}" = "false" ]; then
            echo "Secret is false → true"
          else
            echo "Secret is not false → false"
          fi
