name: Deploy Application A

on:
  workflow_call:
    secrets:
      ALLOW_DEPLOYMENTS:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check if deployment is allowed
        run: |
          echo "🚀 Checking deployment permission..."
          
          if [ "${{ secrets.ALLOW_DEPLOYMENTS }}" = "false" ]; then
            echo "true"
          else
            echo "false"
          fi
