name: Deploy Application A

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check if deployment is allowed
        run: |
          echo "🚀 Checking deployment permission..."
          
          if [ "${{ secrets.ALLOW_DEPLOYMENTS }}" = "true" ]; then
            echo "true"
          else
            echo "false"
          fi
